const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronWebUtils', {
  getPathForFile: (file) => webUtils.getPathForFile(file),
});

contextBridge.exposeInMainWorld('discord', {
  login: (token) => ipcRenderer.invoke('login', token),
  autoLogin: () => ipcRenderer.invoke('auto-login'),
  logout: () => ipcRenderer.invoke('logout'),
  showNotification: (title, body) => ipcRenderer.invoke('show-notification', title, body),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, data) => cb(data)),
  getGuilds: () => ipcRenderer.invoke('get-guilds'),
  getChannels: (guildId) => ipcRenderer.invoke('get-channels', guildId),
  getMessages: (channelId, before) => ipcRenderer.invoke('get-messages', channelId, before),
  sendMessage: (channelId, content, replyToId) => ipcRenderer.invoke('send-message', channelId, content, replyToId),
  sendTyping: (channelId) => ipcRenderer.invoke('send-typing', channelId),
  sendFiles: (channelId, content, replyToId) => ipcRenderer.invoke('send-files', channelId, content, replyToId),
  sendFileBuffers: (channelId, content, replyToId, files) => ipcRenderer.invoke('send-file-buffers', channelId, content, replyToId, files),
  editMessage: (channelId, messageId, content) => ipcRenderer.invoke('edit-message', channelId, messageId, content),
  deleteMessage: (channelId, messageId) => ipcRenderer.invoke('delete-message', channelId, messageId),
  addReaction: (channelId, messageId, emoji) => ipcRenderer.invoke('add-reaction', channelId, messageId, emoji),
  removeReaction: (channelId, messageId, emoji) => ipcRenderer.invoke('remove-reaction', channelId, messageId, emoji),
  fetchReplyMessage: (channelId, messageId) => ipcRenderer.invoke('fetch-reply-message', channelId, messageId),
  getDMChannels: () => ipcRenderer.invoke('get-dm-channels'),
  createDM: (userId) => ipcRenderer.invoke('create-dm', userId),
  getGuildMembers: (guildId) => ipcRenderer.invoke('get-guild-members', guildId),
  getBotUser: () => ipcRenderer.invoke('get-bot-user'),
  getUserProfile: (userId, guildId) => ipcRenderer.invoke('get-user-profile', userId, guildId),
  setUsername: (name) => ipcRenderer.invoke('set-username', name),
  setAvatar: () => ipcRenderer.invoke('set-avatar'),
  selectAvatar: () => ipcRenderer.invoke('select-avatar'),
  confirmAvatar: (base64) => ipcRenderer.invoke('confirm-avatar', base64),
  selectBanner: () => ipcRenderer.invoke('select-banner'),
  confirmBanner: (base64) => ipcRenderer.invoke('confirm-banner', base64),
  setBanner: () => ipcRenderer.invoke('set-banner'),
  removeBanner: () => ipcRenderer.invoke('remove-banner'),
  setStatus: (status) => ipcRenderer.invoke('set-status', status),
  setActivity: (type, name) => ipcRenderer.invoke('set-activity', type, name),
  setNickname: (guildId, nick) => ipcRenderer.invoke('set-nickname', guildId, nick),
  leaveGuild: (guildId) => ipcRenderer.invoke('leave-guild', guildId),
  getGuildInfo: (guildId) => ipcRenderer.invoke('get-guild-info', guildId),
  getGuildEvents: (guildId) => ipcRenderer.invoke('get-guild-events', guildId),
  editGuild: (guildId, data) => ipcRenderer.invoke('edit-guild', guildId, data),
  setGuildIcon: (guildId) => ipcRenderer.invoke('set-guild-icon', guildId),
  getChannelInfo: (channelId) => ipcRenderer.invoke('get-channel-info', channelId),
  editChannel: (channelId, data) => ipcRenderer.invoke('edit-channel', channelId, data),
  createChannel: (guildId, data) => ipcRenderer.invoke('create-channel', guildId, data),
  deleteChannel: (channelId) => ipcRenderer.invoke('delete-channel', channelId),
  cloneChannel: (channelId) => ipcRenderer.invoke('clone-channel', channelId),
  setChannelPermissions: (channelId, targetId, type, allow, deny) => ipcRenderer.invoke('set-channel-permissions', channelId, targetId, type, allow, deny),
  getRoles: (guildId) => ipcRenderer.invoke('get-roles', guildId),
  createRole: (guildId, data) => ipcRenderer.invoke('create-role', guildId, data),
  editRole: (guildId, roleId, data) => ipcRenderer.invoke('edit-role', guildId, roleId, data),
  deleteRole: (guildId, roleId) => ipcRenderer.invoke('delete-role', guildId, roleId),
  addRoleToMember: (guildId, userId, roleId) => ipcRenderer.invoke('add-role-to-member', guildId, userId, roleId),
  removeRoleFromMember: (guildId, userId, roleId) => ipcRenderer.invoke('remove-role-from-member', guildId, userId, roleId),
  kickMember: (guildId, userId, reason) => ipcRenderer.invoke('kick-member', guildId, userId, reason),
  banMember: (guildId, userId, reason, days) => ipcRenderer.invoke('ban-member', guildId, userId, reason, days),
  unbanMember: (guildId, userId) => ipcRenderer.invoke('unban-member', guildId, userId),
  getBans: (guildId) => ipcRenderer.invoke('get-bans', guildId),
  timeoutMember: (guildId, userId, duration) => ipcRenderer.invoke('timeout-member', guildId, userId, duration),
  setMemberNickname: (guildId, userId, nick) => ipcRenderer.invoke('set-member-nickname', guildId, userId, nick),
  moveVoiceMember: (guildId, userId, channelId) => ipcRenderer.invoke('move-voice-member', guildId, userId, channelId),
  setServerMute: (guildId, userId, muted) => ipcRenderer.invoke('set-server-mute', guildId, userId, muted),
  setServerDeaf: (guildId, userId, deafened) => ipcRenderer.invoke('set-server-deaf', guildId, userId, deafened),
  getInvites: (guildId) => ipcRenderer.invoke('get-invites', guildId),
  createInvite: (channelId, opts) => ipcRenderer.invoke('create-invite', channelId, opts),
  deleteInvite: (code) => ipcRenderer.invoke('delete-invite', code),
  getEmojis: (guildId) => ipcRenderer.invoke('get-emojis', guildId),
  createEmoji: (guildId, name) => ipcRenderer.invoke('create-emoji', guildId, name),
  deleteEmoji: (guildId, emojiId) => ipcRenderer.invoke('delete-emoji', guildId, emojiId),
  renameEmoji: (guildId, emojiId, name) => ipcRenderer.invoke('rename-emoji', guildId, emojiId, name),
  getAuditLog: (guildId, limit) => ipcRenderer.invoke('get-audit-log', guildId, limit),
  getWebhooks: (guildId) => ipcRenderer.invoke('get-webhooks', guildId),
  deleteWebhook: (webhookId) => ipcRenderer.invoke('delete-webhook', webhookId),
  pinMessage: (channelId, messageId) => ipcRenderer.invoke('pin-message', channelId, messageId),
  unpinMessage: (channelId, messageId) => ipcRenderer.invoke('unpin-message', channelId, messageId),
  getPinnedMessages: (channelId) => ipcRenderer.invoke('get-pinned-messages', channelId),
  bulkDelete: (channelId, count) => ipcRenderer.invoke('bulk-delete', channelId, count),
  joinVoice: (guildId, channelId) => ipcRenderer.invoke('join-voice', guildId, channelId),
  leaveVoice: (guildId) => ipcRenderer.invoke('leave-voice', guildId),
  startMicrophone: (guildId) => ipcRenderer.invoke('start-microphone', guildId),
  sendMicrophonePCM: (guildId, pcmBuffer) => ipcRenderer.send('microphone-pcm', guildId, pcmBuffer),
  getMicrophoneHealth: (guildId) => ipcRenderer.invoke('get-microphone-health', guildId),
  stopMicrophone: (guildId) => ipcRenderer.invoke('stop-microphone', guildId),
  toggleMute: (guildId) => ipcRenderer.invoke('toggle-mute', guildId),
  toggleDeaf: (guildId) => ipcRenderer.invoke('toggle-deaf', guildId),
  getVoiceChannelMembers: (guildId, channelId) => ipcRenderer.invoke('get-voice-channel-members', guildId, channelId),
  getVoiceState: (guildId) => ipcRenderer.invoke('get-voice-state', guildId),
  onMessageCreate: (cb) => ipcRenderer.on('message-create', (_e, msg) => cb(msg)),
  onMessageUpdate: (cb) => ipcRenderer.on('message-update', (_e, msg) => cb(msg)),
  onMessageDelete: (cb) => ipcRenderer.on('message-delete', (_e, data) => cb(data)),
  onTypingStart: (cb) => ipcRenderer.on('typing-start', (_e, data) => cb(data)),
  onReactionUpdate: (cb) => ipcRenderer.on('reaction-update', (_e, data) => cb(data)),
  onVoiceStateUpdate: (cb) => ipcRenderer.on('voice-state-update', (_e, data) => cb(data)),
  onVoiceSpeaking: (cb) => ipcRenderer.on('voice-speaking', (_e, data) => cb(data)),
  onVoiceDisconnected: (cb) => ipcRenderer.on('voice-disconnected', (_e, data) => cb(data)),
  onVoicePCM: (cb) => ipcRenderer.on('voice-pcm', (_e, pcmBuffer, userId) => cb(pcmBuffer, userId)),
  getAudioDevices: () => ipcRenderer.invoke('get-audio-devices'),
  setAudioDevice: (kind, deviceId) => ipcRenderer.invoke('set-audio-device', kind, deviceId),
  getAudioPrefs: () => ipcRenderer.invoke('get-audio-prefs'),
  onAudioDeviceChanged: (cb) => ipcRenderer.on('audio-device-changed', (_e, data) => cb(data)),
  setHQAudio: (settings) => ipcRenderer.invoke('set-hq-audio', settings),
  getHQAudio: () => ipcRenderer.invoke('get-hq-audio'),
  // Threads
  getThreads: (channelId) => ipcRenderer.invoke('get-threads', channelId),
  getThreadMessages: (threadId, before) => ipcRenderer.invoke('get-thread-messages', threadId, before),
  sendThreadMessage: (threadId, content, replyToId) => ipcRenderer.invoke('send-thread-message', threadId, content, replyToId),
  createThread: (channelId, name, messageId) => ipcRenderer.invoke('create-thread', channelId, name, messageId),
  // Message Search
  searchMessages: (guildId, query, channelId, authorId, limit) => ipcRenderer.invoke('search-messages', guildId, query, channelId, authorId, limit),
  // Soundboard
  playSoundToVoice: (guildId, soundPath, settings) => ipcRenderer.invoke('play-sound-to-voice', guildId, soundPath, settings),
  pauseSoundToVoice: (guildId) => ipcRenderer.invoke('pause-sound-to-voice', guildId),
  resumeSoundToVoice: (guildId) => ipcRenderer.invoke('resume-sound-to-voice', guildId),
  stopSoundToVoice: (guildId) => ipcRenderer.invoke('stop-sound-to-voice', guildId),
  seekSoundToVoice: (guildId, deltaMs) => ipcRenderer.invoke('seek-sound-to-voice', guildId, deltaMs),
  seekSoundToVoiceAbsolute: (guildId, offsetMs) => ipcRenderer.invoke('seek-sound-to-voice-absolute', guildId, offsetMs),
  updateSoundEq: (guildId, settings) => ipcRenderer.invoke('update-sound-eq', guildId, settings),
  onSoundpadState: (cb) => ipcRenderer.on('soundpad-state', (_e, data) => cb(data)),
  selectSoundFile: () => ipcRenderer.invoke('select-sound-file'),
  selectSoundFiles: () => ipcRenderer.invoke('select-sound-files'),
  // Recording
  saveRecording: (wavBuffer, name) => ipcRenderer.invoke('save-recording', wavBuffer, name),
  getRecordingsPath: () => ipcRenderer.invoke('get-recordings-path'),
  deleteRecording: (filePath) => ipcRenderer.invoke('delete-recording', filePath),
  // Keybinds
  registerKeybind: (action, accelerator) => ipcRenderer.invoke('register-keybind', action, accelerator),
  unregisterKeybind: (action) => ipcRenderer.invoke('unregister-keybind', action),
  getKeybinds: () => ipcRenderer.invoke('get-keybinds'),
  saveKeybinds: (keybinds) => ipcRenderer.invoke('save-keybinds', keybinds),
  onKeybindTriggered: (cb) => ipcRenderer.on('keybind-triggered', (_e, action) => cb(action)),
  // Notification Sounds
  playNotificationSound: (type) => ipcRenderer.invoke('play-notification-sound', type),
  onNotificationSound: (cb) => ipcRenderer.on('notification-sound', (_e, data) => cb(data)),
  // Bot Activity
  setBotActivity: (type, name) => ipcRenderer.invoke('set-bot-activity', type, name),
  clearBotActivity: () => ipcRenderer.invoke('clear-bot-activity'),
  // GIF Search
  searchGifs: (query) => ipcRenderer.invoke('search-gifs', query),
  // File Upload (Drag & Drop)
  uploadFile: (channelId, filePath, fileName) => ipcRenderer.invoke('upload-file', channelId, filePath, fileName),
  // TTS
  sendTtsMessage: (channelId, content) => ipcRenderer.invoke('send-tts-message', channelId, content),
  // System Tray
  enableTray: () => ipcRenderer.invoke('enable-tray'),
  disableTray: () => ipcRenderer.invoke('disable-tray'),
  updateTrayBadge: (count) => ipcRenderer.send('update-tray-badge', count),
});

contextBridge.exposeInMainWorld('windowControls', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
});
